name: PR

on: pull_request

jobs:
  initial_pr_scan:
    runs-on: ubuntu-latest
    name: Initial PR scan
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: "Thanks for submitting PR. In case of an emergency merge request, please send an email to `helm-catalog-support at redhat.com`. Otherwise please allow 24 hours for the feedback"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
